services:
  mongodb_recipe:
    image: mongo:latest
    container_name: mongodb_recipe
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: neto
      MONGO_INITDB_ROOT_PASSWORD: neto
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./database/mongo:/docker-entrypoint-initdb.d

  postgres_recipe:
    image: postgres:15-alpine
    container_name: postgres_recipe
    restart: always
    environment:
      POSTGRES_USER: neto
      POSTGRES_PASSWORD: neto
      POSTGRES_DB: recipe_logs_db 
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - 5432:5432
    volumes:
      - pg_log_data:/var/lib/postgresql/data
      - ./database/postgres/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongo_data:
  pg_log_data: