services:
  mongodb_recipe:
    image: mongo:latest
    container_name: mongodb_recipe
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: neto
      MONGO_INITDB_ROOT_PASSWORD: neto
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  cassandra_recipe:
    image: cassandra:latest
    container_name: cassandra_recipe
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-data:/var/lib/cassandra
      - ./init-cassandra.sh:/init-cassandra.sh
