version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: neto
      MONGO_INITDB_ROOT_PASSWORD: neto
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
